Handle long running wal deletion requests
EnterpriseDB/barman pull request #679
Opened 2022-10-17 15:36 UTC by mikewallace1979

Provides two new features to handle requests to delete large volumes of WAL:

1. `--batch-size` parameter which determines the maximum number of objects allowed in a single delete request (#678).
2. `--read-timeout` parameter (AWS only) which allows the boto3 `read_timeout` value to be configured to something other than its default of 60 seconds (#576).

2022-10-18 10:51 UTC, mikewallace1979 commented on barman/cloud.py
> +            raise Exception("Max batch size exceeded")
Sonarqube picked this up as being too general an exception and it's correct - I'll make this more specific.

2022-10-18 18:01 UTC, didiermichel requested changes
I just have some points that can help make the come more explicit.

2022-10-18 18:32 UTC, mikewallace1979 commented on barman/cloud.py
> +            self.delete_batch_size = max(
That's right - `max` is to set a lower bound on the batch size. We can definitely clarify this with a comment.

2022-10-18 18:33 UTC, mikewallace1979 commented on barman/cloud.py
> +        if len(paths) == 0:
Good catch! I brought this code over from the original s3 delete function without really thinking if it was still needed.

2022-10-18 18:34 UTC, mikewallace1979 commented on barman/utils.py
> +def range_fun(*args, **kwargs):
:+1:

2022-10-19 10:02 UTC, didiermichel approved these changes
All fine

2022-10-19 11:27 UTC, merged