Add zstd compression support to Barman Cloud
EnterpriseDB/barman pull request #898
Opened 2024-02-08 02:02 UTC by Jellyfrog

This implements zstandard support to Barman cloud

Quick benchmark (`barman-cloud-backup --cloud-provider aws-s3 s3://test/cloudnativepg/ -J 8 --zstd -h localhost -U postgres postgres`) shows it's the fastest and second smallest size:
| Type | Size | Time |
|--------|--------|--------|
| bz2 | 187.7 MB | 81,26s |
| gz | 250.5 MB | 137,36s |
| snappy | 398.1 MB | 8,41s |
| tar | 945.9 MB | 9,05s |
| zstd | 242.2 MB | 8,24s |

(Please note the benchmark was done against S3 over internet)

2024-02-08 02:03 UTC, Jellyfrog commented
I'll leave this in draft until I tested it more

2024-02-27 17:29 UTC, Jellyfrog commented
Ping @martinmarques

2024-02-28 08:53 UTC, martinmarques commented
> Ping @martinmarques

A little patience, we have some deadlines with products, but this is on our radar and we do want to fully analyse this with the CNPG team. 

More later.

2024-10-08 13:43 UTC, VoVAllen commented
Is there any plan for this to be merged?

2024-10-29 12:06 UTC, gcalacoci requested changes

2024-10-30 11:48 UTC, VoVAllen commented on barman/clients/cloud_compression.py
> +            read_across_frames=True
Hi @gcalacoci I'm interested in finish this. zstd library doesn't seem to have a breaking change with 3.6 and 3.7. Just no longer build the binaries for 3.6 and 3.7. To solve this, we may need a fork of zstd, with some new releases. Does this work with barman? Is EDB interested in holding the fork as well?

2024-10-30 12:19 UTC, Jellyfrog commented on barman/clients/cloud_compression.py
> +            read_across_frames=True
> Hi @gcalacoci I'm interested in finish this. zstd library doesn't seem to have a breaking change with 3.6 and 3.7. Just no longer build the binaries for 3.6 and 3.7. To solve this, we may need a fork of zstd, with some new releases. Does this work with barman? Is EDB interested in holding the fork as well?

Feel free to take over. I’m not going to work on this (especially not for EOL python versions)

2024-10-31 09:13 UTC, martinmarques commented
I'm closing this PR. We plan to add zstd and lz4 support for WAL compression, but we feel the implementation has to cover the whole Barman ecosystem, not just the cloud scripts.

2024-10-31 09:13 UTC, closed without merging

2024-11-12 17:21 UTC, jmealo commented
@martinmarques: I'm looking to roll out CNPG in production, and we'd really prefer to use `lz4` or `zstd` for our backups/archiving. I work at a Python shop and would be happy to contribute work towards this if I have a sponsor to help review the pull request. If you're open to outside contributors, please reach out. I have added support for `lz4` and `zstd` to other streaming compression use cases we had, so I'm somewhat familiar with the process.

I'm assuming the biggest pain here would be including the native dependencies for the Python packages and extending any test harnesses to support it?

2024-11-22 15:29 UTC, martinmarques commented
@jmealo You have that now, as of yesterday