Add `--no-partial` option to `barman-cloud-wal-restore`
EnterpriseDB/barman pull request #930
Opened 2024-06-06 15:47 UTC by mnencia

2024-06-07 06:50 UTC, gbartolini approved these changes

2024-06-07 06:51 UTC, gbartolini commented
Will the documentation be part of the man page (I apologise for the question, but I am not up to date anymore with Barman docs)

2024-06-08 01:05 UTC, barthisrael commented
> Will the documentation be part of the man page (I apologise for the question, but I am not up to date anymore with Barman docs)

I would say yes -- the docs team is working with us to revamp the Barman documentation.
The information from the manual would land on some of the web pages if the current WIP layout ends up being approved  :)

2024-06-08 01:10 UTC, barthisrael requested changes
The PR looks good to me.
I posted a small suggestion to make the changes to the manual more complete.

I performed some test locally and it went fine:

* Archive a partial WAL file:

```console
$ barman-cloud-wal-archive -P barman-cloud --endpoint-url http://localhost:4566 s3://barman-s3-test/ pg17-postgres-default /home/vagrant/barman_home/pg17-postgres-default/streaming/00000001000000000000000F.partial
```

* Attempt to restore that WAL file with `--no-partial` flag -- no success:

```console
$ barman-cloud-wal-restore -P barman-cloud --endpoint-url http://localhost:4566 s3://barman-s3-test/ --no-partial pg17-postgres-default 00000001000000000000000F 00000001000000000000000F

$ echo $?
1

$ ls 00000001000000000000000F
ls: cannot access '00000001000000000000000F': No such file or directory
```

* Attempt to restore that WAL file without `--no-partial` flag -- success:

```console
$ barman-cloud-wal-restore -P barman-cloud --endpoint-url http://localhost:4566 s3://barman-s3-test/ pg17-postgres-default 00000001000000000000000F 00000001000000000000000F

$ echo $?
0

$ ls 00000001000000000000000F
00000001000000000000000F
```

2024-06-11 08:00 UTC, mnencia commented on doc/barman-cloud-wal-restore.1.md
> +  --no-partial          Do not download partial WAL files
added

2024-06-11 08:04 UTC, gcalacoci approved these changes
Patch LGTM, we will merge this soon.

2024-06-11 13:14 UTC, barthisrael approved these changes

2024-06-12 07:27 UTC, martinmarques commented
@gcalacoci should we squash before merging? In any other case, given the reviews this is ready to go into master

2024-06-12 07:35 UTC, merged