Restrict the use of keep annotations to full backups only
EnterpriseDB/barman pull request #947
Opened 2024-06-21 21:32 UTC by bleidens

An incremental backup with the keep annotation that has its parent deleted would become an orphan backup and therefore useless for recovery. To avoid this, we should restrict the use of keep annotations to full backups only. This adds a new check prior to starting the annotation process to make sure we do not allow keeping a backup if it has a parent backup, raising an error if so.

References: BAR-184

2024-06-24 13:55 UTC, gcalacoci commented on barman/cli.py
> +                "Cannot add keep to backup %s because it has a parent backup %s. "
```suggestion
                "Unable to apply the keep flag to backup %s: is an incremental backup. "
```

2024-06-24 13:56 UTC, gcalacoci commented on barman/cli.py
> +                "Only full backups can be kept."
```suggestion
                "Only full backups are eligible to the use of the keep flag."
```

2024-06-24 13:58 UTC, gcalacoci commented on barman/cli.py
> +            ) % (backup_info.backup_id, parent_backup.backup_id)
```suggestion
            ) % (backup_info.backup_id)
```

2024-06-24 14:03 UTC, gcalacoci requested changes
I've reworded the error message.

Regarding your doubts about the location of the check, IMHO your reasoning about applying the check before starting any annotation is valid and in general, the sooner we identify issues like this one, the better.

2024-06-24 15:53 UTC, barthisrael requested changes
The error messages was changed -- unit tests need to be changed accordingly.
After that, squash commits.

2024-06-24 19:16 UTC, barthisrael approved these changes
Looks good.

2024-06-25 12:01 UTC, gcalacoci approved these changes
LGTM now

2024-06-25 12:10 UTC, merged