Require cramjam lib to be >= 2.7.0
EnterpriseDB/barman pull request #958
Opened 2024-07-04 13:39 UTC by gcalacoci

The library `python-snappy` internally uses the library cramjam from versions > 0.6.1.
This doesn't work well with versions of cramjam < 2.7.0 as the structure of the code is different than the one used by python-snappy.

References: bar-156

2024-07-04 15:30 UTC, barthisrael requested changes
Changes look good.

I would extend a bit the commit message with a note explaining that cramjan >= 2.7.0 is not available for Python 3.6, so we need to pin python-snappy to an older version (0.6.1) in that case, to avoid the broken relationship of newer snappy with older cramjan

2024-07-05 12:39 UTC, gcalacoci commented
> Changes look good.
> 
> I would extend a bit the commit message with a note explaining that cramjan >= 2.7.0 is not available for Python 3.6, so we need to pin python-snappy to an older version (0.6.1) in that case, to avoid the broken relationship of newer snappy with older cramjan

I'll rework the commit message. re-reading it doesn't seem clear as it was during the writing

2024-07-08 14:17 UTC, gcalacoci commented
> > Changes look good.
> > I would extend a bit the commit message with a note explaining that cramjan >= 2.7.0 is not available for Python 3.6, so we need to pin python-snappy to an older version (0.6.1) in that case, to avoid the broken relationship of newer snappy with older cramjan
> 
> I'll rework the commit message. re-reading it doesn't seem clear as it was during the writing

re-reading my commit message:
```
Also for python < 3.7 new `cramjam` libs are not available.

So we pinned `python-snappy` to 0.6.1 for python < 3.7, and set use
the new `python-snappy` and `cramjam` versions for python >= 3.7 .
```
@barthisrael you think is not understandable enough?

2024-07-09 14:31 UTC, barthisrael commented
@gcalacoci I think the second looks good.

2024-07-09 15:04 UTC, barthisrael approved these changes
Looks great!

2024-07-09 15:13 UTC, merged