Add check of backup compression when taking incremental backups
EnterpriseDB/barman pull request #979
Opened 2024-08-06 19:33 UTC by andremagui

Backups taken with `pg_basebackup` can get compression. On the other hand, incremental backups cannot be taken on top of compressed parent backups nor they can be taken with `backup_compression` configuration set.

This PR is adding those checks before taking any incremental backup and the unit tests for both use cases.

References: BAR-253

2024-08-08 00:59 UTC, barthisrael requested changes

2024-08-08 21:29 UTC, andremagui commented on tests/test_backup.py
> +        [("gzip", None), ("gzip", "gzip"), (None, "gzip"), (None, None)],
Great tip! Thanks

2024-08-12 10:09 UTC, gcalacoci commented on barman/backup.py
> +                    "Incremental backups cannot be taken on top of compressed backups."
Another option:
```suggestion
                    "The specified backup cannot be a parent for an "
                    "incremental backup. Reason: "
                    "Compressed backups are not eligible as parents of incremental backups."
```

Possibly we should get some help from a native English speaker, no matter how I try to change this we continue to repeat `parent` and `incremental backups` 😓

2024-08-12 18:09 UTC, barthisrael commented on barman/backup.py
> +                    "Incremental backups cannot be taken on top of compressed backups."
I'm ok with Giulio's suggestion as well.

2024-08-12 18:51 UTC, barthisrael reviewed
The code changes look fine, the unit tests as well.
We only need to apply the suggestion in regards to the message.

But this is working as expected.

# Able to take backup when no compression is involved

```console
# Check compression config
$ barman diagnose | jq '.servers.pg17.config | {backup_method,backup_compression}'
{
  "backup_method": "postgres",
  "backup_compression": null
}

# Check compression of the parent
$ barman diagnose | jq '.servers.pg17.backups."20240812T201751" | {backup_name,mode,compression}'
{
  "backup_name": "full",
  "mode": "postgres",
  "compression": null
}

# Attempt a backup from that parent
$ barman backup pg17 --name incremental --incremental full
Starting backup using postgres method for server pg17 in /home/vagrant/barman_home/pg17/base/20240812T201955
Backup start at LSN: 8/4B0000C8 (00000001000000080000004B, 000000C8)
Starting backup copy via pg_basebackup for 20240812T201955
Copy done (time: 2 seconds)
Finalising the backup.
Backup size: 3.4 MiB
Backup end at LSN: 8/4D000000 (00000001000000080000004D, 00000000)
Backup completed (start time: 2024-08-12 20:19:55.417281, elapsed time: 2 seconds)
Processing xlog segments from streaming for pg17
	00000001000000080000004B
	00000001000000080000004C
WARNING: IMPORTANT: this backup is classified as WAITING_FOR_WALS, meaning that Barman has not received yet all the required WAL files for the backup consistency.
This is a common behaviour in concurrent backup scenarios, and Barman automatically set the backup as DONE once all the required WAL files have been archived.
Hint: execute the backup command with '--wait'
```

# Not able to take backup when parent is compressed

```console
# Check compression config
$ barman diagnose | jq '.servers.pg17.config | {backup_method,backup_compression}'
{
  "backup_method": "postgres",
  "backup_compression": null
}

# Check compression of the parent
$ barman diagnose | jq '.servers.pg17.backups."20240812T201751" | {backup_name,mode,compression}'
{
  "backup_name": "full",
  "mode": "postgres",
  "compression": "gzip"
}

# Attempt a backup from that parent
$ barman backup pg17 --name incremental --incremental full
ERROR: failed to start backup: Incremental backups cannot be taken on top of compressed backups.
```

# Not able to take backup when compression is enabled

```console
# Check compression config
$ barman diagnose | jq '.servers.pg17.config | {backup_method,backup_compression}'
{
  "backup_method": "postgres",
  "backup_compression": "gzip"
}

# Attempt a compressed incremental backup
$ barman backup pg17 --name incremental --incremental full
ERROR: failed to start backup: Incremental backups cannot be taken with 'backup_compression' set in the configuration options.
```

2024-08-13 15:53 UTC, gcalacoci approved these changes

2024-08-13 15:53 UTC, merged