Add "snapshot" backup type to `list-backup` output
EnterpriseDB/barman pull request #984
Opened 2024-08-08 21:34 UTC by bleidens

Update `backup_type` property to also return the label for snapshot backups and adjust the unit tests accordingly. Since the updates to the `list-backup` command introduced by BAR-207 on adding backup type information to the output did not account for snapshot backups, this update fixes this oversight.

References: BAR-268

2024-08-12 19:18 UTC, barthisrael requested changes
The changes here are simple and look good.
I'm only missing a "why" in the commit message, i.e. it was an oversight in the original implementation.

2024-08-13 18:35 UTC, barthisrael requested changes

2024-08-13 18:35 UTC, barthisrael commented on barman/infofile.py
> +        if self.mode == "snapshot":
This won't work because `backup.info` stores `mode=snapshot-concurrent`, e.g.

I'd say to check the prefix in case of `snapshot` and `rsync` modes.

2024-08-14 00:27 UTC, barthisrael approved these changes
This looks good now. I have all types of backups here, and these are sample outputs:

* Console mode:

```console
postgres 20240814T015515 'dev_postgres_incremental' - I - Wed Aug 14 01:55:17 2024 - Size: 35.0 MiB - WAL Size: 16.0 MiB
postgres 20240814T015504 'dev_postgres_full' - F - Wed Aug 14 01:55:06 2024 - Size: 54.3 MiB - WAL Size: 32.0 MiB
rsync 20240814T015530 'dev_rsync' - R - Wed Aug 14 01:55:33 2024 - Size: 38.1 MiB - WAL Size: 0 B
snapshot 20240814T015546 'dev_snapshot' - S - Tue Aug 13 23:56:34 2024 - Size: 16.0 MiB - WAL Size: 0 B
```

* JSON mode:

```console
$ barman -f json list-backup all | jq
{
  "postgres": [
    {
      "backup_id": "20240814T015515",
      "backup_name": "dev_postgres_incremental",
      "backup_type": "incremental",
      "end_time": "Wed Aug 14 01:55:17 2024",
      "end_time_timestamp": "1723593317",
      "retention_status": "-",
      "size": "35.0 MiB",
      "size_bytes": 36661108,
      "status": "DONE",
      "wal_size": "16.0 MiB",
      "wal_size_bytes": 16777216
    },
    {
      "backup_id": "20240814T015504",
      "backup_name": "dev_postgres_full",
      "backup_type": "full",
      "end_time": "Wed Aug 14 01:55:06 2024",
      "end_time_timestamp": "1723593306",
      "retention_status": "-",
      "size": "54.3 MiB",
      "size_bytes": 56945916,
      "status": "DONE",
      "wal_size": "32.0 MiB",
      "wal_size_bytes": 33554432
    }
  ],
  "rsync": [
    {
      "backup_id": "20240814T015530",
      "backup_name": "dev_rsync",
      "backup_type": "rsync",
      "end_time": "Wed Aug 14 01:55:33 2024",
      "end_time_timestamp": "1723593333",
      "retention_status": "-",
      "size": "38.1 MiB",
      "size_bytes": 40002684,
      "status": "DONE",
      "wal_size": "0 B",
      "wal_size_bytes": 0
    }
  ],
  "snapshot": [
    {
      "backup_id": "20240814T015546",
      "backup_name": "dev_snapshot",
      "backup_type": "snapshot",
      "end_time": "Tue Aug 13 23:56:34 2024",
      "end_time_timestamp": "1723593394",
      "retention_status": "-",
      "size": "16.0 MiB",
      "size_bytes": 16778289,
      "status": "DONE",
      "wal_size": "0 B",
      "wal_size_bytes": 0
    }
  ]
}
```

2024-08-14 13:15 UTC, gcalacoci approved these changes
<ignore this, i've approved by mistake>

2024-08-15 12:08 UTC, barthisrael approved these changes
Looks good!

* Console format:

```console
$ barman list-backup all
postgres 20240814T182116 'dev_postgres_incremental' - I - Wed Aug 14 18:21:18 2024 - Size: 35.1 MiB - WAL Size: 16.0 MiB
postgres 20240814T182104 'dev_postgres_full' - F - Wed Aug 14 18:21:07 2024 - Size: 314.0 MiB - WAL Size: 32.0 MiB
rsync 20240814T182130 'dev_rsync' - R - Wed Aug 14 18:21:35 2024 - Size: 297.8 MiB - WAL Size: 0 B
snapshot 20240814T182150 'dev_snapshot' - S - Wed Aug 14 16:22:38 2024 - Size: 16.0 MiB - WAL Size: 16.0 MiB
```

* JSON format:

```console
$ barman -f json list-backup all | jq | egrep "backup_(type|name)"
      "backup_name": "dev_postgres_incremental",
      "backup_type": "incremental",
      "backup_name": "dev_postgres_full",
      "backup_type": "full",
      "backup_name": "dev_rsync",
      "backup_type": "rsync",
      "backup_name": "dev_snapshot",
      "backup_type": "snapshot",
```

2024-08-15 12:09 UTC, merged